vi = norm(birdStorage(BIRD.vx:BIRD.vz, itr, t));
simplifiedLift = vi^2/CONSTANTS.v0^2 * CONSTANTS.M * CONSTANTS.g * ...
    birdStorage(BIRD.ezx:BIRD.ezz, itr, t);
simplifiedDrag = CONSTANTS.CL_CD*vi^2/CONSTANTS.v0^2 * CONSTANTS.M * ...
    CONSTANTS.g * birdStorage(BIRD.ezx:BIRD.ezz, itr, t);
thrust = CONSTANTS.T0 * birdStorage(BIRD.exx:BIRD.exz, itr, t);

flightForce = simplifiedLift + ...
    simplifiedDrag + ...
    thrust + ...
    (CONSTANTS.M * [0;0;-CONSTANTS.g])